#! /bin/bash

# Deployd logs don't have timestamps, so make each execution a little easier to track
echo "$(date '+%Y-%m-%d %H:%M:%S')"

# Needed here as well since /var/log/druid is shared between container and host
sudo mkdir -p /var/log/druid/gc
sudo chmod 777 -R /var/log/druid/

sudo mkdir -p /mnt/druid/tmp
sudo chmod 777 -R /mnt/druid/

DEPLOY_TYPE="${TELETRAAN_DEPLOY_TYPE}"

case "${DEPLOY_TYPE}" in
    dev1)
        configure-serviceset -c teletraan/${ENV_NAME}/telefig/serviceset.dev1.conf
        ;;
    insights)
        configure-serviceset -c teletraan/${ENV_NAME}/telefig/serviceset.insights.conf
        ;;
    spam)
        configure-serviceset -c teletraan/${ENV_NAME}/telefig/serviceset.spam.conf
        ;;
    adsexp)
        configure-serviceset -c teletraan/${ENV_NAME}/telefig/serviceset.adsexp.conf
        ;;
    *)
        echo "Unsupported DEPLOY_TYPE: '${DEPLOY_TYPE}'"
        exit 1
esac
