#!/bin/bash

if [ -e /tmp/deploy/${ENV_NAME}/STOPPING ]; then
    cd /tmp/deploy/${ENV_NAME}
    ./STOPPING
    # Delete previous artifact's clean up scripts so we use our own going forward
    rm -r /tmp/deploy/${ENV_NAME}
else
    DEPLOY_TYPE="${TELETRAAN_DEPLOY_TYPE}"
    case "${DEPLOY_TYPE}" in
        dev1)
            configure-serviceset stop -c teletraan/${ENV_NAME}/telefig/serviceset.dev1.conf
            ;;
        insights)
            configure-serviceset stop -c teletraan/${ENV_NAME}/telefig/serviceset.insights.conf
            ;;
        spam)
            configure-serviceset stop -c teletraan/${ENV_NAME}/telefig/serviceset.spam.conf
            ;;
        adsexp)
            configure-serviceset stop -c teletraan/${ENV_NAME}/telefig/serviceset.adsexp.conf
            ;;

        *)
            echo "Unsupported DEPLOY_TYPE: '${DEPLOY_TYPE}'"
            exit 1
    esac

fi